//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterBillingDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuMaster
    {
        public int ID { get; set; }
        public string MenuName { get; set; }
        public string MenuDes { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ParentMenuID { get; set; }
        public Nullable<int> refMenuGroupId { get; set; }
        public int OrderNo { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string MenuPath { get; set; }
    
        public virtual MenuMaster MenuMaster1 { get; set; }
        public virtual MenuMaster MenuMaster2 { get; set; }
    }
}
