//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterBillingDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDetail
    {
        public int Id { get; set; }
        public int RefCollectionCenterId { get; set; }
        public decimal CounterNo { get; set; }
        public int ReceiptNo { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public int RefConsumerId { get; set; }
        public decimal RecAmt { get; set; }
        public int RefPaymentTypeId { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string IsChqStatus { get; set; }
        public string ChqBounceRefNo { get; set; }
        public Nullable<System.DateTime> ChqBounceDate { get; set; }
        public Nullable<decimal> ChqBounceCharge { get; set; }
        public Nullable<decimal> DPCBal { get; set; }
        public Nullable<decimal> DPCPaid { get; set; }
        public Nullable<decimal> BasicBal { get; set; }
        public Nullable<decimal> BasicPaid { get; set; }
        public Nullable<decimal> BasicBalPending { get; set; }
        public Nullable<decimal> DPCBalPending { get; set; }
        public Nullable<decimal> TillDateDPC { get; set; }
        public int InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public string InsTerminal { get; set; }
        public Nullable<int> UpdUser { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public string UpdTerminal { get; set; }
    
        public virtual ConsumerMaster ConsumerMaster { get; set; }
        public virtual MasterValue MasterValue { get; set; }
        public virtual MasterValue MasterValue1 { get; set; }
    }
}
